-- Add table with LGD classes and class id-s
ALTER TABLE public.classes DROP COLUMN id;
INSERT INTO public.classes VALUES
                               ('Abbey'),
                               ('AdministrativeBoundary'),
                               ('AerialwayGoods'),
                               ('AerialwayStation'),
                               ('AerialwayThing'),
                               ('AlcoholShop'),
                               ('AntiquesShop'),
                               ('ApartmentBuilding'),
                               ('ApplianceShop'),
                               ('ArchaeologicalSite'),
                               ('ArtShop'),
                               ('ArtsCentre'),
                               ('ArtShop'),
                               ('Artwork'),
                               ('ATM'),
                               ('Attraction'),
                               ('BabyGoods'),
                               ('BagsShop'),
                               ('Bakery'),
                               ('Bank'),
                               ('Bar'),
                               ('Battlefield'),
                               ('BathroomFurnishing'),
                               ('Bay'),
                               ('Beach'),
                               ('BeautyShop'),
                               ('Bedrock'),
                               ('BedShop'),
                               ('Bench'),
                               ('BicycleParking'),
                               ('BicycleRental'),
                               ('BicycleShop'),
                               ('Biergarten'),
                               ('BookmakerShop'),
                               ('BooksShop'),
                               ('Boundary'),
                               ('BoundaryForest'),
                               ('BoundaryMarker'),
                               ('BoundaryStone'),
                               ('Boutique'),
                               ('Bridge'),
                               ('Bridge_site'),
                               ('Bridleway'),
                               ('Brownfield'),
                               ('Building'),
                               ('BuildingBarn'),
                               ('BuildingBunker'),
                               ('BuildingCabin'),
                               ('BuildingChapel'),
                               ('BuildingChurch'),
                               ('BuildingCommercial'),
                               ('BuildingDormitory'),
                               ('BuildingGarage'),
                               ('BuildingHospital'),
                               ('BuildingHut'),
                               ('BuildingKiosk'),
                               ('BuildingOffice'),
                               ('BuildingResidential'),
                               ('BuildingRetail'),
                               ('BuildingSchool'),
                               ('BureauDeChange'),
                               ('BusStop'),
                               ('Butcher'),
                               ('CableCar'),
                               ('Cafe'),
                               ('CameraShop'),
                               ('Cape'),
                               ('Carpet'),
                               ('CarRental'),
                               ('CarSharing'),
                               ('CarShop'),
                               ('CarWash'),
                               ('Casino'),
                               ('Castle'),
                               ('Cave'),
                               ('CaveEntrance'),
                               ('Cemetery'),
                               ('ChairLift'),
                               ('Channel'),
                               ('CharityShop'),
                               ('Cheese'),
                               ('Chemist'),
                               ('Childcare'),
                               ('Chocolate'),
                               ('Cinema'),
                               ('City'),
                               ('CityGate'),
                               ('CityLimit'),
                               ('CivilBoundary'),
                               ('Cliff'),
                               ('Clinic'),
                               ('Clock'),
                               ('Clothes'),
                               ('Coastline'),
                               ('CoffeeShop'),
                               ('Col'),
                               ('Collapsed'),
                               ('College'),
                               ('CommercialLanduse'),
                               ('CommunityCentre'),
                               ('Computer'),
                               ('Confectionery'),
                               ('Construction'),
                               ('Convenience'),
                               ('Copyshop'),
                               ('Cosmetics'),
                               ('Courthouse'),
                               ('Crafts'),
                               ('Crater'),
                               ('Courthouse'),
                               ('Cycling'),
                               ('Cycleway'),
                               ('Dance'),
                               ('Deli'),
                               ('Dentist'),
                               ('DepartmentStore'),
                               ('Detached'),
                               ('Doctors'),
                               ('DragLift'),
                               ('DrinkingWater'),
                               ('DryCleaning'),
                               ('ElectronicsShop'),
                               ('Elevator'),
                               ('EstateAgent'),
                               ('Fabric'),
                               ('FashionShop'),
                               ('FastFood'),
                               ('Fell'),
                               ('Fen'),
                               ('FireStation'),
                               ('FitnessCentre'),
                               ('Fjord'),
                               ('Florist'),
                               ('Footway'),
                               ('Fort'),
                               ('Fountain'),
                               ('Fraternity'),
                               ('FuneralDirectors'),
                               ('Furniture'),
                               ('Gallery'),
                               ('Gambling'),
                               ('Games'),
                               ('Garage'),
                               ('Garden'),
                               ('Geyser'),
                               ('Gift'),
                               ('GiveWaySign'),
                               ('Glacier'),
                               ('Glaziery'),
                               ('Gondola'),
                               ('GovernmentBuilding'),
                               ('Grassland'),
                               ('GrassLanduse'),
                               ('Greengrocer'),
                               ('GritBin'),
                               ('GuestHouse'),
                               ('Hackerspace'),
                               ('Hairdresser'),
                               ('Hardware'),
                               ('Headland'),
                               ('HealthFood'),
                               ('HearingAids'),
                               ('Heath'),
                               ('Heritage'),
                               ('Hifi'),
                               ('HighwayConstruction'),
                               ('HighwayCrossing'),
                               ('HighwayPrimaryLink'),
                               ('HighwaySecondaryLink'),
                               ('HighwayService'),
                               ('HighwayTertiaryLink'),
                               ('Hill'),
                               ('HistoricBuilding'),
                               ('HistoricChapel'),
                               ('HistoricChurch'),
                               ('HistoricFountain'),
                               ('HistoricHouse'),
                               ('HistoricIndustrial'),
                               ('HistoricMarker'),
                               ('HistoricMilestone'),
                               ('HistoricMine'),
                               ('HistoricMonastery'),
                               ('HistoricMuseum'),
                               ('HistoricPointOfInterest'),
                               ('HistoricStatue'),
                               ('HistoricTower'),
                               ('HistoricWell'),
                               ('HistoricThing'),
                               ('HobbyShop'),
                               ('HomeFurnishing'),
                               ('Hospital'),
                               ('Hostel'),
                               ('Hotel'),
                               ('House'),
                               ('Housewares'),
                               ('IceCream'),
                               ('Icon'),
                               ('IndustrialLanduse'),
                               ('IndustrialProductionBuilding'),
                               ('InternetCafe'),
                               ('Island'),
                               ('Jewelry'),
                               ('Kindergarten'),
                               ('Kiosk'),
                               ('KitchenShop'),
                               ('Land'),
                               ('LanguageSchool'),
                               ('Laundry'),
                               ('Lavoir'),
                               ('Leisure'),
                               ('Library'),
                               ('Lighting'),
                               ('LivingStreet'),
                               ('Locksmith'),
                               ('Manor'),
                               ('MaritimeBoundary'),
                               ('Marsh'),
                               ('MassageShop'),
                               ('Marketplace'),
                               ('Meadow'),
                               ('Memorial'),
                               ('Menhir'),
                               ('MiniRoundabout'),
                               ('Mill'),
                               ('MineShaft'),
                               ('MixedLift'),
                               ('MobilePhone'),
                               ('Monument'),
                               ('Monastery'),
                               ('Moor'),
                               ('Motorcycle'),
                               ('Motorway'),
                               ('MountainPass'),
                               ('MountainRange'),
                               ('Mud'),
                               ('Museum'),
                               ('Mushroom'),
                               ('Music'),
                               ('MusicalInstrument'),
                               ('NationalPark'),
                               ('NaturalBench'),
                               ('NaturalRiver'),
                               ('NaturalRock'),
                               ('NaturalThing'),
                               ('NaturalValley'),
                               ('NaturalWaterfall'),
                               ('NatureReserve'),
                               ('Newsagent'),
                               ('Nightclub'),
                               ('OpticianShop'),
                               ('Outdoor'),
                               ('Paint'),
                               ('Palace'),
                               ('Park'),
                               ('Parking'),
                               ('ParkingEntrance'),
                               ('ParkingSpace'),
                               ('Pastry'),
                               ('Path'),
                               ('Peak'),
                               ('PedestrianUse'),
                               ('Peninsula'),
                               ('Perfumery'),
                               ('PetShop'),
                               ('Pharmacy'),
                               ('Photo'),
                               ('PicnicSite'),
                               ('Pitch'),
                               ('PlaceOfWorship'),
                               ('Plain'),
                               ('Plateau'),
                               ('Platform'),
                               ('Playground'),
                               ('Police'),
                               ('PoliticalBoundary'),
                               ('PostBox'),
                               ('PostOffice'),
                               ('Pottery'),
                               ('PrimaryHighway'),
                               ('ProposedHighway'),
                               ('ProtectedArea'),
                               ('ProtectedBuilding'),
                               ('Pub'),
                               ('PublicBuilding'),
                               ('Pylon'),
                               ('Raceway'),
                               ('RailwayLanduse'),
                               ('Recycling'),
                               ('Reef'),
                               ('Region'),
                               ('Religious'),
                               ('Rent'),
                               ('ResidentialHighway'),
                               ('ResidentialLanduse'),
                               ('RestArea'),
                               ('Restaurant'),
                               ('RetailLanduse'),
                               ('Ridge'),
                               ('Rock'),
                               ('Road'),
                               ('Ruins'),
                               ('RuneStone'),
                               ('SaintsCross'),
                               ('Sand'),
                               ('Sauna'),
                               ('School'),
                               ('Scree'),
                               ('Scrub'),
                               ('Sea'),
                               ('SecondaryHighway'),
                               ('SecondaryLink'),
                               ('SecondHand'),
                               ('Service'),
                               ('Shed'),
                               ('Shelter'),
                               ('Shoal'),
                               ('Shoes'),
                               ('Shop'),
                               ('SocialFacility'),
                               ('SpeedCamera'),
                               ('SportsCentre'),
                               ('SportsShop'),
                               ('Spring'),
                               ('Square'),
                               ('Stationery'),
                               ('Steps'),
                               ('Stone'),
                               ('StoneCircle'),
                               ('Strait'),
                               ('StreetLamp'),
                               ('Stripclub'),
                               ('Studio'),
                               ('Suburb'),
                               ('Supermarket'),
                               ('Synagogue'),
                               ('Tailor'),
                               ('Tanning'),
                               ('Tattoo'),
                               ('Taxi'),
                               ('Tea'),
                               ('Telecommunication'),
                               ('Telephone'),
                               ('Terrace'),
                               ('TertiaryHighway'),
                               ('Ticket'),
                               ('Tobacco'),
                               ('Toilets'),
                               ('Tombstone'),
                               ('TourismInformation'),
                               ('TourismThing'),
                               ('Townhall'),
                               ('Toys'),
                               ('Track'),
                               ('TrafficSignals'),
                               ('TrainStation'),
                               ('TravelAgency'),
                               ('Tree'),
                               ('TreeRow'),
                               ('Trunk'),
                               ('TrunkLink'),
                               ('Tumulus'),
                               ('TurningCircle'),
                               ('University'),
                               ('UnclassifiedHighway'),
                               ('Vacant'),
                               ('VendingMachine'),
                               ('Veterinary'),
                               ('VideoGames'),
                               ('VideoShop'),
                               ('Viewpoint'),
                               ('VillageGreen'),
                               ('Volcano'),
                               ('WasteBasket'),
                               ('WasteDisposal'),
                               ('Watches'),
                               ('Water'),
                               ('Waterhole'),
                               ('WaterPark'),
                               ('WaysideChapel'),
                               ('WaysideCross'),
                               ('WaysideShrine'),
                               ('Wetland'),
                               ('Wine'),
                               ('Wood'),
                               ('Wreck');
ALTER TABLE public.classes ADD COLUMN class_id SERIAL PRIMARY KEY;


-- Clean up entities table and add constraints
-- Clean up some weird id-s
UPDATE public."association_osm" SET osm_id= -osm_id WHERE association_osm.osm_id<0;

-- Remove duplicates based on osm_id
DELETE
FROM public.entities
WHERE ctid IN
      (
          SELECT ctid
          FROM(
                  SELECT
                      *,
                      ctid,
                      row_number() OVER (PARTITION BY osm_id ORDER BY ctid)
                  FROM public.entities
              )s
          WHERE row_number >= 2
      );

-- Add respective constraints and primary keys
ALTER TABLE public."entities" ADD CONSTRAINT unique_osmid UNIQUE ("osm_id");
ALTER TABLE ONLY public."entities"
    ADD CONSTRAINT prk_osmid PRIMARY KEY ("osm_id");

-- Reshape linkage table
-- Add constraints to linkage table
ALTER TABLE public.association_osm ADD COLUMN id SERIAL PRIMARY KEY;
-- Ensure all osm_id values are TEXT
ALTER TABLE public.entities
ALTER COLUMN osm_id type TEXT using osm_id::TEXT;


-- Add more spatial indexes for GEOGRAPHY datatype
CREATE INDEX classes_geog ON public.entities USING gist(CAST(geom AS geography));

-- Drop tables generated by default by osm2pgsql
DROP TABLE planet_osm_nodes;
DROP TABLE planet_osm_ways;
DROP TABLE planet_osm_rels;

-- Fix osm_id type in entities table
ALTER TABLE entities
ALTER COLUMN osm_id TYPE BIGINT USING osm_id::NUMERIC;


-- Add region name to entities table
ALTER TABLE entities ADD COLUMN region_id INT;
UPDATE entities t1
SET region_id = t2.gid
    FROM region_south_tyrol t2
WHERE ST_Contains(t2.geom, ST_CENTROID(t1.geom));


-- Create table for region spatial relations
CREATE TABLE region_spatial_relations AS
WITH pairs AS (
    SELECT
        a.gid AS gid1,
        b.gid AS gid2
    FROM region_south_tyrol a
             JOIN region_south_tyrol b ON a.gid < b.gid
)
SELECT
    p.gid1,
    p.gid2,
    CASE
        WHEN ST_DWithin(a.geom::geography, b.geom::geography, 50) THEN 'borderby'
        WHEN ST_Distance(a.geom::geography, b.geom::geography) <= 5000 THEN 'nearby'
        ELSE NULL
        END AS relation
FROM pairs p
         JOIN region_south_tyrol a ON p.gid1 = a.gid
         JOIN region_south_tyrol b ON p.gid2 = b.gid
WHERE ST_Distance(a.geom::geography, b.geom::geography) <= 5000;